# chain_width = 5
comment_width = 60
force_explicit_abi = true
hard_tabs = false
imports_granularity = "Crate"
max_width = 80
merge_derives = true
newline_style = "Auto"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
